id: I34FA2598
default_language: zh
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:58.643209
last_modified: 2023-01-04 11:31:58.643221
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  79C9:
    title: Pithy Advice on Checking One's Progress on the Path
    base_file: 79C9.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
